# Generated by Django 5.2.7 on 2025-10-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastalik', '0003_post_likes_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
