# Generated by Django 5.2.7 on 2025-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastalik', '0004_chatmessage_image_alter_chatmessage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('misir', '🌽 Mısır'), ('bugday', '🌾 Buğday'), ('mercimek', '🌱 Mercimek'), ('sebze', '🥕 Sebze'), ('hayvancilik', '🐄 Hayvancılık'), ('genel', '🗣️ Genel')], default='genel', max_length=20),
        ),
    ]
